### PR TITLE
UnixDirectoryParser is not reading the last modified from files

### PR DESCRIPTION
**Pull request by guilhermelabigalini**
UnixDirectoryParser is not reading the last modified from files, this can be fixed by reading the field "date" from the regular expression groups.

### CODE REVIEW

**Comment by guilhermelabigalini** [comment]
Hi Nick, thanks for the great component, I'm using it with a project targeting .net core and its being very helpful, but we identified that in Unix servers its not reading the file date/time change, looking the code the change seems to be only in the UnixDirectoryParser in the regular expression reader...

Would be possible to release a new version with this fix? 

Thanks again!

**Comment by sparkeh9** [comment]
Sorry for the delay, your change is most welcome (the wonders of open source) :)

The change will be in v1.1.5

**Comment by sparkeh9** [comment]
https://www.nuget.org/packages/CoreFtp/1.1.5

**Comment by guilhermelabigalini** [comment]
thanks a lot!

**Pull request merged**
